services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    command: pnpm start:prod:migrate
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_starter
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
